# Generated by Django 5.2.3 on 2025-06-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defualt.png', upload_to='profile_pics'),
        ),
    ]
