# Generated by Django 5.2.3 on 2025-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='null'),
        ),
    ]
