# Generated by Django 5.2.3 on 2025-06-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=False, upload_to='photos/%y/%m/%d'),
        ),
    ]
